# Generated by Django 5.0.6 on 2024-05-18 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laptopAllocation', '0002_remove_allocation_laptop_remove_allocation_student_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.IntegerField(editable=False, unique=True)),
                ('time_slot', models.CharField(choices=[('09-09:45', '09-09:45 '), ('10-10:45', '10-10:45 '), ('11-11:45', '11-11:45 '), ('12-12:45', '12-12:45 '), ('02-02:45', '02-02:45 ')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(editable=False, unique=True)),
                ('model_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=100)),
                ('date_of_joining', models.DateField()),
                ('company_laptop_required', models.BooleanField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptopAllocation.batch')),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_allocation', models.DateField()),
                ('date_of_return', models.DateField()),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptopAllocation.laptop')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptopAllocation.student')),
            ],
        ),
    ]
