# Generated by Django 5.0.6 on 2024-05-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptopAllocation', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='date_of_allocation',
            field=models.DateField(null=True),
        ),
    ]
