# Generated by Django 5.0.6 on 2024-05-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptopAllocation', '0004_alter_allocation_date_of_allocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='date_of_allocation',
            field=models.DateField(blank=True, null=True),
        ),
    ]
