# Generated by Django 5.0.6 on 2024-05-18 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptopAllocation', '0006_remove_allocation_date_of_allocation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Allocation',
        ),
    ]
