# Generated by Django 5.0.6 on 2024-05-18 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptopAllocation', '0007_delete_allocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_allocation', models.DateField()),
                ('date_of_return', models.DateField(null=True)),
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptopAllocation.laptop')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptopAllocation.student')),
            ],
        ),
    ]
