# Generated by Django 5.0.6 on 2024-05-19 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laptopAllocation', '0008_allocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allocation',
            name='date_of_return',
        ),
    ]
