# Generated by Django 5.0.6 on 2024-05-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptopAllocation', '0009_remove_allocation_date_of_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='serial_number',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
